### ISSUE TITLE
run_invsigma.py fails due to not finding slvr.model.bglen_mask 

### ISSUE THREAD

**Issue by bearecinos** [EdiGlacUQ/fenics_ice#54]
Hi @dngoldberg, 

I was running `run_invsigma.py` yesterday and there is an issue regarding the bglen_mask (smith.toml includes this and also the input data, previous stages worked except this one)

[in this line:  self.fl_ex = slvr.bglen_data_conditional(slvr.H,slvr.model.bglen_mask)](https://github.com/EdiGlacUQ/fenics_ice/blob/main/fenics_ice/prior.py#L303):

```
def __init__(self, slvr, space):
        """Get flotation condition & delta_beta_gnd"""
        self.fl_ex = slvr.bglen_data_conditional(slvr.H, slvr.model.bglen_mask)
        self.delta_beta_gnd = slvr.delta_beta_gnd

        super().__init__(slvr, space)
``` 

Basically the error outputs that the object `slvr.model.bglen_mask` is not defined in model? I also looked if this is defined in model and I could not find it anywhere in the code?

```
Traceback (most recent call last):
  File "/exports/csce/datastore/geos/users/brecinos/fenics_ice/runs/run_invsigma.py", line 388, in <module>
    run_invsigma(sys.argv[1])
  File "/exports/csce/datastore/geos/users/brecinos/fenics_ice/runs/run_invsigma.py", line 159, in run_invsigma
    reg_op = Prior(slvr, space)
  File "/exports/csce/datastore/geos/users/brecinos/fenics_ice/fenics_ice/prior.py", line 303, in __init__
    self.fl_ex = slvr.bglen_data_conditional(slvr.H,slvr.model.bglen_mask)
AttributeError: 'model' object has no attribute 'bglen_mask'
```

**Comment by bearecinos** [comment]
Should this be: `self.model.bglen_mask` instead of slvr?

**Comment by bearecinos** [comment]
I think the problem is how things are defined inside [solver.py -> bglen_data_conditional](https://github.com/EdiGlacUQ/fenics_ice/blob/main/fenics_ice/solver.py#L1056-L1078)

```
def bglen_data_conditional(self, H, glen_mask, H_float=None):
        """Compute a ufl Conditional where floating=1, grounded=0"""

        if not self.params.ice_dynamics.allow_flotation:
            fl_beta_mask = ufl.operators.Conditional(ufl.eq(self.model.bglen_mask,1.0), 
                                          Constant(1.0, cell=triangle, name="Const data"),
                                          Constant(0.0, cell=triangle, name="Const no data"))
        else:

            if H_float is None:
             constants = self.params.constants
             rhow = constants.rhow
             rhoi = constants.rhoi
             H_float = -(rhow/rhoi) * self.bed


            fl_beta_mask = ufl.operators.Conditional(ufl.operators.And(H > H_float, ufl.eq(self.model.bglen_mask,1.0)),
                                          Constant(1.0, cell=triangle, name="Const data"),
                                          Constant(0.0, cell=triangle, name="Const no data"))

        # Note: cell=triangle just suppresses a UFL warning ("missing cell")

        return fl_beta_mask
```

**Comment by bearecinos** [comment]
from @dngoldberg:

This gets fix by calling: 
```
mdl.bglen_from_data(mask_only=True)
```

in [run_invsigma.py#L148](https://github.com/EdiGlacUQ/fenics_ice/blob/main/runs/run_invsigma.py#L148)
